### PR TITLE
Let ghtar always use latest version by default & mongodb bugfix

### LINKED ISSUE #1124: Unable to compile mongodb on Linux x64
I am unable to compile PHP (tried 8.5 - 8.3) with mongodb on Linux x64 using the latest stable spc code via composer.

Error:
> config.status: error: cannot find input file: 'src/libmongoc/src/common/src/common-config.h.in'

Config:
```
libs: nghttp2,liblz4
debug: true
extensions: intl,pdo_sqlite,sqlite3,curl,openssl,tokenizer,bcmath,bz2,calendar,dba,ftp,iconv,mysqli,mbstring,mbregex,xml,simplexml,ctype,dom,pdo,filter,session,zlib,fileinfo,pdo_mysql,posix,sockets,shmop,sodium,sysvmsg,sysvsem,sysvshm,gd,zip,gmp,redis,xmlwriter,phar,exif,xmlreader,readline,pcntl,soap,imagick,ffi,password-argon2,pgsql,pdo_pgsql,imap,ldap,xsl,igbinary,zstd,gettext,mongodb,sqlsrv,pdo_sqlsrv,opcache
no-strip: true
```

```
2026-04-29T09:26:48.9441444Z configure: patching main/php_config.h.in
2026-04-29T09:26:48.9459402Z configure: creating ./config.status
2026-04-29T09:26:48.9776290Z creating main/internal_functions.c
2026-04-29T09:26:49.0721447Z creating main/internal_functions_cli.c
2026-04-29T09:26:49.1729083Z config.status: error: cannot find input file: 'src/libmongoc/src/common/src/common-config.h.in'
2026-04-29T09:26:49.2069785Z [31m✗ Command execution failed: Command exited with non-zero code: 1[0m
2026-04-29T09:26:49.2070058Z [31m----------------------------------------[0m
2026-04-29T09:26:49.2070247Z [31m[0m
2026-04-29T09:26:49.2070377Z [31mFailed module: [33mBuilder for Linux[0m[0m
2026-04-29T09:26:49.2070507Z [31m[0m
2026-04-29T09:26:49.2078053Z [31mFailed command: [33mCFLAGS='-g -Os' CPPFLAGS='-I/app/buildroot/include' LDFLAGS='-L/app/buildroot/lib' ./configure --prefix= --with-valgrind=no --disable-shared --enable-static --disable-all --disable-phpdbg --with-pic --enable-cli --enable-fpm --disable-embed --disable-micro --disable-cgi --with-config-file-path=/usr/local/etc/php --with-config-file-scan-dir=/usr/local/etc/php/conf.d --enable-intl --enable-pdo --with-sqlite3=/app/buildroot --with-pdo-sqlite --with-curl --with-zlib --with-zlib-dir=/app/buildroot --with-openssl=/app/buildroot --with-openssl-dir=/app/buildroot --enable-tokenizer --enable-bcmath --with-bz2=/app/buildroot --enable-calendar --enable-dba --enable-ftp --with-iconv=/app/buildroot --enable-mysqlnd --with-mysqli --enable-mbstring --enable-mbregex --enable-xml --with-libxml="/app/buildroot" --enable-simplexml --with-libxml="/app/buildroot" --enable-ctype --enable-dom --with-libxml="/app/buildroot" --enable-filter --enable-session --enable-fileinfo --with-pdo-mysql --enable-posix --enable-sockets --enable-shmop --with-sodium --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-gd --with-freetype --with-jpeg --with-webp --with-zip=/app/buildroot --with-gmp=/app/buildroot --enable-igbinary --enable-redis --enable-redis-session --enable-redis-igbinary --disable-redis-msgpack --enable-redis-zstd --with-libzstd="/app/buildroot" --enable-redis-lz4 --with-liblz4="/app/buildroot" --enable-xmlwriter --with-libxml="/app/buildroot" --enable-phar --enable-exif --enable-xmlreader --with-libxml="/app/buildroot" --with-libedit --without-readline --enable-pcntl --enable-soap --with-libxml="/app/buildroot" --with-imagick=/app/buildroot ac_cv_func_omp_pause_resource_all=no --with-ffi --enable-zend-signals --with-password-argon2 --with-pgsql=/app/buildroot --with-pdo-pgsql=/app/buildroot --with-imap=/app/buildroot --with-imap-ssl=/app/buildroot --with-ldap=/app/buildroot --with-xsl=/app/buildroot --enable-zstd --with-libzstd="/app/buildroot" --with-gettext=/app/buildroot --enable-mongodb --with-mongodb-system-libs=no --with-mongodb-client-side-encryption=no --with-mongodb-sasl=no --with-mongodb-ssl=openssl --with-mongodb-icu=yes --with-mongodb-zstd=yes --with-mongodb-zlib=yes --enable-sqlsrv --with-pdo-sqlsrv --enable-opcache --enable-opcache-jit[0m[0m
```

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Fix #1124

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [ ] `composer cs-fix`
  - [ ] `composer analyse`
  - [ ] `composer test`
  - [ ] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [ ] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

File: tests/mock/SPC_store.php [hunk 1]
```diff
@@ -12,6 +12,15 @@
...
     $result_code = 0;
+    if (str_contains($command, 'https://api.github.com/repos/AOMediaCodec/libavif/releases/latest')) {
+        $output = explode("\n", json_encode([
+            'tag_name' => 'v1.1.1',
+            'tarball_url' => 'https://api.github.com/repos/AOMediaCodec/libavif/tarball/v1.1.1',
+            'prerelease' => false,
+            'draft' => false,
+        ]));
+        return true;
+    }
```
Comment (henderkes) [inline tests/mock/SPC_store.php:23]: I don't understand why this is required

Comment (crazywhalecc) [reply tests/mock/SPC_store.php:23]: We dont' really fetch info from API, this is a full-mock functions for curlExec for stablize tests.

**Review by henderkes — APPROVED** [review]
