### PR TITLE
Patch pkg-config and la files with placeholder when packing pre-built content

### LINKED ISSUE #829: Pre-built content contains `libxxx.la` with wrong `-LXXX/lib` locations
Just download a random libs to reproduce: https://github.com/static-php/static-php-cli-hosted/releases/download/2025.6.12/xz-aarch64-linux-musl-1.2.5.txz

Image

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Patch pkg-config and la files with placeholder when packing pre-built content, fixes #829 

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [X] `PHP_CS_FIXER_IGNORE_ENV=1 composer cs-fix`
  - [X] `composer analyse`
  - [X] `composer test`
  - [X] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [ ] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

**Review by henderkes — APPROVED** [review]
I haven't tested it, but I don't see anything wrong. Looks good.

**Comment by henderkes** [comment]
Looks like the openssl prefix change didn't work.

File: src/SPC/builder/linux/library/openssl.php [hunk 1]
```diff
@@ -67,26 +67,26 @@ public function build(): void
         shell()->cd($this->source_dir)->initializeEnv($this)
             ->exec(
                 "{$env} ./Configure no-shared {$extra} " .
-                '--prefix=/ ' .
-                '--libdir=lib ' .
+                '--prefix=' . BUILD_ROOT_PATH . ' ' .
+                '--libdir=' . BUILD_LIB_PATH . ' ' .
```
Comment (henderkes) [inline src/SPC/builder/linux/library/openssl.php:71]: guess this didn't work?

Comment (henderkes) [reply src/SPC/builder/linux/library/openssl.php:71]: oh my browser didn't refresh fast enough x)
