### PR TITLE
Fix global env manager, add in-ini variable parsing

### LINKED ISSUE #805: The variable in env.ini not working
<summary>
<details>

```
$ bin/spc-alpine-docker build swoole --debug --build-cli
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.6.1
                             |_|         |_|
[09:22:12] [D] argv: bin/spc build swoole --debug --build-cli
[09:22:12] [D] Setting env: PATH=/app/buildroot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[09:22:12] [D] Setting env: PKG_CONFIG=/app/buildroot/bin/pkg-config
[09:22:12] [D] Setting env: PKG_CONFIG_PATH=/app/buildroot/lib/pkgconfig
[09:22:12] [D] Setting env: SPC_LINUX_DEFAULT_CC=gcc
[09:22:12] [D] Setting env: SPC_LINUX_DEFAULT_CXX=g++
[09:22:12] [D] Setting env: SPC_LINUX_DEFAULT_AR=ar
[09:22:12] [D] Setting env: SPC_LINUX_DEFAULT_LD=ld.gold
[09:22:12] [D] Setting env: SPC_CONCURRENCY=12
[09:22:12] [D] Setting env: SPC_SKIP_PHP_VERSION_CHECK=no
[09:22:12] [D] Setting env: SPC_SKIP_DOCTOR_CHECK_ITEMS=
[09:22:12] [D] Setting env: SPC_CMD_VAR_FRANKENPHP_XCADDY_MODULES=--with github.com/dunglas/frankenphp/caddy --with github.com/dunglas/mercure/caddy --with github.com/dunglas/vulcain/caddy --with github.com/dunglas/caddy-cbrotli
[09:22:12] [D] Setting env: SPC_LIBC=musl
[09:22:12] [D] Setting env: CC=gcc
[09:22:12] [D] Setting env: CXX=g++
[09:22:12] [D] Setting env: AR=ar
[09:22:12] [D] Setting env: LD=ld.gold
[09:22:12] [D] Setting env: SPC_DEFAULT_C_FLAGS=-fPIC -Os -U_FORTIFY_SOURCE
[09:22:12] [D] Setting env: SPC_DEFAULT_CXX_FLAGS=-fPIC -Os
[09:22:12] [D] Setting env: SPC_EXTRA_LIBS=
[09:22:12] [D] Setting env: UPX_EXEC=/app/pkgroot/bin/upx
[09:22:12] [D] Setting env: SPC_MICRO_PATCHES=static_extensions_win32,cli_checks,disable_huge_page,vcruntime140,win32,zend_stream
[09:22:12] [D] Setting env: SPC_CMD_PREFIX_PHP_BUILDCONF=./buildconf --force
[09:22:12] [D] Setting env: SPC_CMD_PREFIX_PHP_CONFIGURE=./configure --prefix= --with-valgrind=no --disable-shared --enable-static --disable-all --disable-cgi --disable-phpdbg --with-pic
[09:22:12] [D] Setting env: SPC_CMD_PREFIX_PHP_MAKE=make -j12
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_EMBED_TYPE=static
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS= -fPIE
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS=-I/app/buildroot/include
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS=-L/app/buildroot/lib
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_LIBS=-ldl -lpthread -lm
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS=-g -fstack-protector-strong -fno-ident -fPIE 
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS=-ldl -lpthread -lm
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS=
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS_PROGRAM=-all-static -Wl,-O1 -pie
[09:22:12] [D] Dir /app/buildroot/lib/pkgconfig already exists, ignored
[09:22:12] [D] Dir /app/buildroot/include already exists, ignored
[09:22:12] [D] Init var [BUILD_ROOT_PATH]:                            /app/buildroot
[09:22:12] [D] Init var [BUILD_INCLUDE_PATH]:                         /app/buildroot/include
[09:22:12] [D] Init var [BUILD_LIB_PATH]:                             /app/buildroot/lib
[09:22:12] [D] Init var [BUILD_BIN_PATH]:                             /app/buildroot/bin
[09:22:12] [D] Init var [PKG_ROOT_PATH]:                              /app/pkgroot
[09:22:12] [D] Init var [SOURCE_PATH]:                                /app/source
[09:22:12] [D] Init var [DOWNLOAD_PATH]:                              /app/downloads
[09:22:12] [D] Init var [CPU_COUNT]:                                  12
[09:22:12] [D] Init var [SPC_ARCH]:                                   aarch64
[09:22:12] [D] Init var [GNU_ARCH]:                                   aarch64
[09:22:12] [D] Init var [MAC_ARCH]:                                   arm64
[09:22:12] [D] Init var [PATH]:                                       /app/buildroot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[09:22:12] [D] Init var [PKG_CONFIG]:                                 /app/buildroot/bin/pkg-config
[09:22:12] [D] Init var [PKG_CONFIG_PATH]:                            /app/buildroot/lib/pkgconfig
[09:22:12] [D] Init var [SPC_LINUX_DEFAULT_CC]:                       gcc
[09:22:12] [D] Init var [SPC_LINUX_DEFAULT_CXX]:                      g++
[09:22:12] [D] Init var [SPC_LINUX_DEFAULT_AR]:                       ar
[09:22:12] [D] Init var [SPC_LINUX_DEFAULT_LD]:                       ld.gold
[09:22:12] [D] Init var [SPC_CONCURRENCY]:                            12
[09:22:12] [D] Init var [SPC_SKIP_PHP_VERSION_CHECK]:                 no
[09:22:12] [D] Init var [SPC_SKIP_DOCTOR_CHECK_ITEMS]:                
[09:22:12] [D] Init var [SPC_CMD_VAR_FRANKENPHP_XCADDY_MODULES]:      --with github.com/dunglas/frankenphp/caddy --with github.com/dunglas/mercure/caddy --with github.com/dunglas/vulcain/caddy --with github.com/dunglas/caddy-cbrotli
[09:22:12] [D] Init var [SPC_LIBC]:                                   musl
[09:22:12] [D] Init var [CC]:                                         gcc
[09:22:12] [D] Init var [CXX]:                                        g++
[09:22:12] [D] Init var [AR]:                                         ar
[09:22:12] [D] Init var [LD]:                                         ld.gold
[09:22:12] [D] Init var [SPC_DEFAULT_C_FLAGS]:                        -fPIC -Os -U_FORTIFY_SOURCE
[09:22:12] [D] Init var [SPC_DEFAULT_CXX_FLAGS]:                      -fPIC -Os
[09:22:12] [D] Init var [SPC_EXTRA_LIBS]:                             
[09:22:12] [D] Init var [UPX_EXEC]:                                   /app/pkgroot/bin/upx
[09:22:12] [D] Init var [SPC_MICRO_PATCHES]:                          static_extensions_win32,cli_checks,disable_huge_page,vcruntime140,win32,zend_stream
[09:22:12] [D] Init var [SPC_CMD_PREFIX_PHP_BUILDCONF]:               ./buildconf --force
[09:22:12] [D] Init var [SPC_CMD_PREFIX_PHP_CONFIGURE]:               ./configure --prefix= --with-valgrind=no --disable-shared --enable-static --disable-all --disable-cgi --disable-phpdbg --with-pic
[09:22:12] [D] Init var [SPC_CMD_PREFIX_PHP_MAKE]:                    make -j12
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_EMBED_TYPE]:                 static
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS]:            -fPIE
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS]:         -I/app/buildroot/include
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS]:          -L/app/buildroot/lib
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_LIBS]:             -ldl -lpthread -lm
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS]:          -g -fstack-protector-strong -fno-ident -fPIE 
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS]:            -ldl -lpthread -lm
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS]:         
[09:22:12] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS_PROGRAM]: -all-static -Wl,-O1 -pie
[09:22:12] [I] Build OS:              Linux (aarch64)
[09:22:12] [I] Build SAPI:            cli
[09:22:12] [I] Static Extensions (4): zlib,openssl,curl,swoole
[09:22:12] [I] Shared Extensions (0): 
[09:22:12] [I] Libraries (10):        pkg-config,zlib,openssl,brotli,nghttp2,libcares,curl
[09:22:12] [I] Strip Binaries:        yes
[09:22:12] [I] Enable ZTS:            no
[09:22:12] [I] Config File Path:      /usr/local/etc/php
[09:22:12] [I] PHP Version:           8.4.8
[09:22:12] [I] Extra Exts (3):        zlib, openssl, curl
[09:22:12] [N] Build will start after 2s ...
^C[09:22:13] [D] scanning directory /app/src/SPC/builder/linux/library
[09:22:13] [D] enabling nghttp2 without libxml2
[09:22:13] [D] enabling nghttp2 without nghttp3
[09:22:13] [D] enabling nghttp2 without ngtcp2
[09:22:13] [D] enabling curl without libssh2
[09:22:13] [D] enabling curl without nghttp3
[09:22:13] [D] enabling curl without ngtcp2
[09:22:13] [D] enabling curl without zstd
[09:22:13] [D] scanning directory /app/src/SPC/builder/extension
[09:22:13] [D] [EXEC] ldd 2>&1
[09:22:13] [D] Executed at: /app/src/SPC/util/UnixShell.php:95
[09:22:13] [D] Source [php-src] already extracted in /app/source/php-src, skip !
[09:22:13] [D] Source [micro] already extracted in /app/source/php-src/sapi/micro, skip !
[09:22:13] [W] Lock entry for 'swoole' has 'source_type' set to 'dir', which is deprecated. Please re-download your dependencies.
[09:22:13] [W] Lock entry for 'swoole' has 'source_type' set to 'dir', which is deprecated. Please re-download your dependencies.
[09:22:13] [W] Lock entry for 'swoole' has 'source_type' set to 'dir', which is deprecated. Please re-download your dependencies.
[09:22:13] [D] Source [swoole] already extracted in /app/source/php-src/ext/swoole, skip !
[09:22:13] [I] enabling swoole without extension swoole-hook-pgsql
[09:22:13] [I] enabling swoole without extension swoole-hook-mysql
[09:22:13] [I] enabling swoole without extension swoole-hook-sqlite
[09:22:13] [N] lib [pkg-config] already built
[09:22:13] [N] lib [zlib] already built
[09:22:13] [N] lib [openssl] already built
[09:22:13] [N] lib [brotli] already built
[09:22:13] [N] lib [nghttp2] already built
[09:22:13] [N] lib [libcares] already built
[09:22:13] [N] lib [curl] already built
[09:22:13] [D] Removing path recursively: "/app/buildroot/modules"
[09:22:13] [D] Scan dir failed, no such file or directory.
[09:22:13] [D] Setting env: SPC_EXTRA_LIBS=/app/buildroot/lib/libcurl.a /app/buildroot/lib/libcares.a /app/buildroot/lib/libnghttp2.a /app/buildroot/lib/libbrotlidec.a /app/buildroot/lib/libbrotlienc.a /app/buildroot/lib/libbrotlicommon.a /app/buildroot/lib/libssl.a /app/buildroot/lib/libcrypto.a /app/buildroot/lib/libz.a -lstdc++ 
[09:22:13] [D] Setting env: CFLAGS=-fPIC -Os -U_FORTIFY_SOURCE
[09:22:13] [I] patching before-configure for curl checks
[09:22:13] [I] Extension [curl] patched before buildconf
[09:22:13] [D] Replacing file with type[1]: /app/source/php-src/build/php.m4
[09:22:13] [I] Entering dir: /app/source/php-src
[09:22:13] [I] [EXEC] ./buildconf --force
[09:22:13] [D] Executed at: /app/src/SPC/util/UnixShell.php:47
[09:22:13] [D] [PASSTHRU] cd '/app/source/php-src' && ./buildconf --force
buildconf: Checking installation
buildconf: autoconf version 2.72 (ok)
buildconf: Forcing buildconf. The configure files will be regenerated.
buildconf: Cleaning cache and configure files
buildconf: Rebuilding configure
^C[09:22:14] [E] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/app/source/php-src' && ./buildconf --force at /app/src/globals/functions.php(177)
[09:22:14] [E] #0 /app/src/SPC/util/UnixShell.php(51): f_passthru('cd '/app/source...')
#1 /app/src/SPC/builder/linux/LinuxBuilder.php(90): SPC\util\UnixShell->exec('cd '/app/source...')
#2 /app/src/SPC/command/BuildPHPCommand.php(208): SPC\builder\linux\LinuxBuilder->buildPHP(1)
#3 /app/src/SPC/command/BaseCommand.php(107): SPC\command\BuildPHPCommand->handle()
#4 /app/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildPHPCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/bin/spc(31): Symfony\Component\Console\Application->run()
#9 {main}
/Users/jerry/project/git-project/static-php-cli (fix/ext-imap-extraction*) $ 
/Users/jerry/project/git-project/static-php-cli (fix/ext-imap-extraction*) $ bin/spc build swoole --debug --build-cli       
     _        _   _                 _
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.6.1
                             |_|         |_|
[09:22:59] [D] argv: bin/spc build swoole --debug --build-cli
[09:22:59] [D] Setting env: PATH=/Users/jerry/project/git-project/static-php-cli/buildroot/bin:/opt/homebrew/bin:/Users/jerry/Library/Application Support/Herd/config/nvm/versions/node/v22.9.0/bin:/Users/jerry/.pyenv/shims:/opt/homebrew/opt/openjdk@21/bin:/Users/jerry/go/bin:/Users/jerry/Library/Python/3.9/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/mysql@5.7/bin:/usr/local/sbin:/usr/local/bin:/Users/jerry/.composer/vendor/bin:/Users/jerry/tools/bin:/Users/jerry/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/Users/jerry/project/git-project/static-php-cli/node_modules/.bin
[09:22:59] [D] Setting env: PKG_CONFIG=/Users/jerry/project/git-project/static-php-cli/buildroot/bin/pkg-config
[09:22:59] [D] Setting env: PKG_CONFIG_PATH=/Users/jerry/project/git-project/static-php-cli/buildroot/lib/pkgconfig
[09:22:59] [D] Setting env: SPC_CONCURRENCY=12
[09:22:59] [D] Setting env: SPC_SKIP_PHP_VERSION_CHECK=no
[09:22:59] [D] Setting env: SPC_SKIP_DOCTOR_CHECK_ITEMS=
[09:22:59] [D] Setting env: SPC_CMD_VAR_FRANKENPHP_XCADDY_MODULES=--with github.com/dunglas/frankenphp/caddy --with github.com/dunglas/mercure/caddy --with github.com/dunglas/vulcain/caddy --with github.com/dunglas/caddy-cbrotli
[09:22:59] [D] Setting env: CC=clang
[09:22:59] [D] Setting env: CXX=clang++
[09:22:59] [D] Setting env: SPC_DEFAULT_C_FLAGS=--target=arm64-apple-darwin -Os
[09:22:59] [D] Setting env: SPC_DEFAULT_CXX_FLAGS=--target=arm64-apple-darwin -Os
[09:22:59] [D] Setting env: SPC_EXTRA_LIBS=
[09:22:59] [D] Setting env: SPC_MICRO_PATCHES=static_extensions_win32,cli_checks,disable_huge_page,vcruntime140,win32,zend_stream,macos_iconv
[09:22:59] [D] Setting env: SPC_CMD_PREFIX_PHP_BUILDCONF=./buildconf --force
[09:22:59] [D] Setting env: SPC_CMD_PREFIX_PHP_CONFIGURE=./configure --prefix= --with-valgrind=no --enable-shared=no --enable-static=yes --disable-all --disable-cgi --disable-phpdbg
[09:22:59] [D] Setting env: SPC_CMD_PREFIX_PHP_MAKE=make -j12
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS= -Werror=unknown-warning-option
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS=-I/Users/jerry/project/git-project/static-php-cli/buildroot/include
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS=-L/Users/jerry/project/git-project/static-php-cli/buildroot/lib
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS=-g -fstack-protector-strong -fpic -fpie 
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS=-lresolv
[09:22:59] [D] Setting env: SPC_CMD_VAR_PHP_EMBED_TYPE=static
[09:22:59] [D] Dir /Users/jerry/project/git-project/static-php-cli/buildroot/lib/pkgconfig already exists, ignored
[09:22:59] [D] Dir /Users/jerry/project/git-project/static-php-cli/buildroot/include already exists, ignored
[09:22:59] [D] Init var [BUILD_ROOT_PATH]:                       /Users/jerry/project/git-project/static-php-cli/buildroot
[09:22:59] [D] Init var [BUILD_INCLUDE_PATH]:                    /Users/jerry/project/git-project/static-php-cli/buildroot/include
[09:22:59] [D] Init var [BUILD_LIB_PATH]:                        /Users/jerry/project/git-project/static-php-cli/buildroot/lib
[09:22:59] [D] Init var [BUILD_BIN_PATH]:                        /Users/jerry/project/git-project/static-php-cli/buildroot/bin
[09:22:59] [D] Init var [PKG_ROOT_PATH]:                         /Users/jerry/project/git-project/static-php-cli/pkgroot
[09:22:59] [D] Init var [SOURCE_PATH]:                           /Users/jerry/project/git-project/static-php-cli/source
[09:22:59] [D] Init var [DOWNLOAD_PATH]:                         /Users/jerry/project/git-project/static-php-cli/downloads
[09:22:59] [D] Init var [CPU_COUNT]:                             12
[09:22:59] [D] Init var [SPC_ARCH]:                              arm64
[09:22:59] [D] Init var [GNU_ARCH]:                              aarch64
[09:22:59] [D] Init var [MAC_ARCH]:                              arm64
[09:22:59] [D] Init var [PATH]:                                  /Users/jerry/project/git-project/static-php-cli/buildroot/bin:/opt/homebrew/bin:/Users/jerry/Library/Application Support/Herd/config/nvm/versions/node/v22.9.0/bin:/Users/jerry/.pyenv/shims:/opt/homebrew/opt/openjdk@21/bin:/Users/jerry/go/bin:/Users/jerry/Library/Python/3.9/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/mysql@5.7/bin:/usr/local/sbin:/usr/local/bin:/Users/jerry/.composer/vendor/bin:/Users/jerry/tools/bin:/Users/jerry/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/Users/jerry/project/git-project/static-php-cli/node_modules/.bin
[09:22:59] [D] Init var [PKG_CONFIG]:                            /Users/jerry/project/git-project/static-php-cli/buildroot/bin/pkg-config
[09:22:59] [D] Init var [PKG_CONFIG_PATH]:                       /Users/jerry/project/git-project/static-php-cli/buildroot/lib/pkgconfig
[09:22:59] [D] Init var [SPC_CONCURRENCY]:                       12
[09:22:59] [D] Init var [SPC_SKIP_PHP_VERSION_CHECK]:            no
[09:22:59] [D] Init var [SPC_SKIP_DOCTOR_CHECK_ITEMS]:           
[09:22:59] [D] Init var [SPC_CMD_VAR_FRANKENPHP_XCADDY_MODULES]: --with github.com/dunglas/frankenphp/caddy --with github.com/dunglas/mercure/caddy --with github.com/dunglas/vulcain/caddy --with github.com/dunglas/caddy-cbrotli
[09:22:59] [D] Init var [CC]:                                    clang
[09:22:59] [D] Init var [CXX]:                                   clang++
[09:22:59] [D] Init var [SPC_DEFAULT_C_FLAGS]:                   --target=arm64-apple-darwin -Os
[09:22:59] [D] Init var [SPC_DEFAULT_CXX_FLAGS]:                 --target=arm64-apple-darwin -Os
[09:22:59] [D] Init var [SPC_EXTRA_LIBS]:                        
[09:22:59] [D] Init var [SPC_MICRO_PATCHES]:                     static_extensions_win32,cli_checks,disable_huge_page,vcruntime140,win32,zend_stream,macos_iconv
[09:22:59] [D] Init var [SPC_CMD_PREFIX_PHP_BUILDCONF]:          ./buildconf --force
[09:22:59] [D] Init var [SPC_CMD_PREFIX_PHP_CONFIGURE]:          ./configure --prefix= --with-valgrind=no --enable-shared=no --enable-static=yes --disable-all --disable-cgi --disable-phpdbg
[09:22:59] [D] Init var [SPC_CMD_PREFIX_PHP_MAKE]:               make -j12
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS]:       -Werror=unknown-warning-option
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS]:    -I/Users/jerry/project/git-project/static-php-cli/buildroot/include
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS]:     -L/Users/jerry/project/git-project/static-php-cli/buildroot/lib
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS]:     -g -fstack-protector-strong -fpic -fpie 
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS]:       -lresolv
[09:22:59] [D] Init var [SPC_CMD_VAR_PHP_EMBED_TYPE]:            static
[09:22:59] [I] Build OS:              Darwin (arm64)
[09:22:59] [I] Build SAPI:            cli
[09:22:59] [I] Static Extensions (4): zlib,openssl,curl,swoole
[09:22:59] [I] Shared Extensions (0): 
[09:22:59] [I] Libraries (10):        pkg-config,zlib,openssl,brotli,nghttp2,libcares,curl
[09:22:59] [I] Strip Binaries:        yes
[09:22:59] [I] Enable ZTS:            no
[09:22:59] [I] Config File Path:      /usr/local/etc/php
[09:22:59] [I] PHP Version:           8.4.8
[09:22:59] [I] Extra Exts (3):        zlib, openssl, curl
[09:22:59] [N] Build will start after 2s ...
```

</details>
</summary>

- `SPC_DEFAULT_C_FLAGS="-fPIC -Os -U_FORTIFY_SOURCE"`
- `SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS="-g -fstack-protector-strong -fno-ident -fPIE ${SPC_DEFAULT_C_FLAGS}"`

We got:

```
[09:22:12] [D] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS=-g -fstack-protector-strong -fno-ident -fPIE 
```

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Fixes #805 

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [x] `PHP_CS_FIXER_IGNORE_ENV=1 composer cs-fix`
  - [x] `composer analyse`
  - [x] `composer test`
  - [x] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [ ] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

File: src/SPC/util/GlobalEnvManager.php [hunk 1]
```diff
@@ -55,10 +53,73 @@ public static function init(?BuilderBase $builder = null): void
                 self::putenv("SPC_LINUX_DEFAULT_CXX={$arch}-linux-musl-g++");
                 self::putenv("SPC_LINUX_DEFAULT_AR={$arch}-linux-musl-ar");
                 self::putenv("SPC_LINUX_DEFAULT_LD={$arch}-linux-musl-ld");
```
Comment (henderkes) [inline src/SPC/util/GlobalEnvManager.php:55]: I would like to move away from this, but probably better to do when I finish zig support and 16.0 releases.

File: src/SPC/util/GlobalEnvManager.php [hunk 2]
```diff
@@ -55,10 +53,73 @@ public static function init(?BuilderBase $builder = null): void
...
+            default => [],
+        };
+        foreach ($os_ini as $k => $v) {
+            if (getenv($k) === false) {
+                $default_put_list[$k] = $v;
+                self::putenv("{$k}={$v}");
+            }
+        }
+        // apply second time
+        $ini2 = self::readIniFile();
```
Comment (henderkes) [inline src/SPC/util/GlobalEnvManager.php:84]: instead of duplicating the code here, run it in a foreach ([0, 1] as $i) loop.

**Review by henderkes — CHANGES_REQUESTED** [review]

File: src/SPC/util/GlobalEnvManager.php (hunk 2 above)
Comment (crazywhalecc) [reply src/SPC/util/GlobalEnvManager.php:84]: No, it's not same. It has different `if` statement in 2nd cycle: `if (isset($default_put_list[$k]) && $default_put_list[$k] !== $v)`

Comment (henderkes) [reply src/SPC/util/GlobalEnvManager.php:84]: Okay!

**Review by henderkes — APPROVED** [review]
