### PR TITLE
Fix nghttp2 and curl build configurations for static linking

### LINKED ISSUE #1013: Curl library: links against nghttp2.dll
CMake Warning:
  Manually-specified variables were not used by the project:

    CURL_STATICLIB
    NGHTTP2_CFLAGS

Therefore it never gets -DNGHTTP2_STATICLIB and links against __imp__... symbols.

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Closes #1013

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [ ] `composer cs-fix`
  - [ ] `composer analyse`
  - [ ] `composer test`
  - [ ] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [X] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

File: src/SPC/builder/windows/library/curl.php [hunk 1]
```diff
@@ -53,5 +52,7 @@ protected function build(): void
             );
         // move libcurl.lib to libcurl_a.lib
         rename(BUILD_LIB_PATH . '\libcurl.lib', BUILD_LIB_PATH . '\libcurl_a.lib');
+
+        FileSystem::replaceFileStr(BUILD_INCLUDE_PATH . '\curl\curl.h', '#ifdef CURL_STATICLIB', '#if 1');
```
Comment (henderkes) [inline src/SPC/builder/windows/library/curl.php:56]: We should add  the definition to CMAKE_C_FLAGS instead.

File: src/SPC/builder/windows/library/nghttp2.php [hunk 2]
```diff
@@ -29,11 +29,16 @@ protected function build(): void
...
+                '-DENABLE_STATIC_CRT=ON ' .
+                '-DENABLE_DOC=OFF ' .
+                '-DBUILD_TESTING=OFF '
             )
             ->execWithWrapper(
                 $this->builder->makeSimpleWrapper('cmake'),
                 "--build build --config Release --target install -j{$this->builder->concurrency}"
             );
+
+        FileSystem::replaceFileStr(BUILD_INCLUDE_PATH . '\nghttp2\nghttp2.h', '#ifdef NGHTTP2_STATICLIB', '#if 1');
```
Comment (henderkes) [inline src/SPC/builder/windows/library/nghttp2.php:42]: and the same here

File: src/SPC/builder/windows/library/curl.php (hunk 1 above)
Comment (crazywhalecc) [reply src/SPC/builder/windows/library/curl.php:56]: Since we have no unified cflags env var for Windows builder, the last executable build will always need it if depending on it. That's not appropriate for current build dependency tree. We have to change many other libs/executables cflags.

In v3 I implemented WindowsCMakeExecutor which may do this properly. it is more important to treat it as a permanent static library to avoid linking issues just for now, I think.

Comment (henderkes) [reply src/SPC/builder/windows/library/curl.php:56]: Hmm, I haven't looked the windows stuff much, so I'll take your word for it.

Go 1.26 lets us compile cgo with clang on Windows, so this unlocks a msvc backend. In other words frankenphp is soon windows compatible, but the thought of distributing 800mb worth of dll's just to run it seems insane to me.

**Review by henderkes — APPROVED** [review]
