### PR TITLE
fix: icu-static-win, ext-swoole, krb5

### LINKED ISSUE #1060: Swoole build bug on gnu-docker
https://github.com/static-php/static-php-cli-hosted/actions/runs/22979862291/job/66717031332#step:10:29406

### LINKED ISSUE #1083: Build failed after adding sqlsrv,pdo_sqlsrv
before:
https://github.com/nujz/static-php-cli/actions/runs/23989890412/job/69967714799

after:
https://github.com/nujz/static-php-cli/actions/runs/23995256144/job/69982134882

### LINKED ISSUE #1084: Followed From CLI Build Command Generator and got error
```
[12:41:06] [D] Making new directory recursive: C:\spc2\buildroot/source-licenses/freetype
[12:41:06] [I] lib [freetype] setup success, took 17.93 s
[12:41:06] [I] Building required lib [icu-static-win]
[12:41:06] [D] Extracting source [icu-static-win] to C:\spc2\source\icu-static-win ...
[12:41:06] [I] Extracting icu-static-win source to C:\spc2\source\icu-static-win ...
[12:41:06] [D] Extracting source [archive]: C:\spc2\downloads/icu-static-windows-x64.zip
[12:41:06] [D] Making new directory recursive: C:\spc2\source\icu-static-win
[12:41:06] [D] Making new directory recursive: C:\Users\User\AppData\Local\Temp\spc_unzip_c0a0c760ee5e04729a8fd92684e222f6
[12:41:06] [D] [PASSTHRU] "C:\spc2\php-sdk-binary-tools\bin\7za.exe" x C:\spc2\downloads\icu-static-windows-x64.zip -oC:\Users\User\AppData\Local\Temp\spc_unzip_c0a0c760ee5e04729a8fd92684e222f6 -y

7-Zip (a) 25.01 (x86) : Copyright (c) 1999-2025 Igor Pavlov : 2025-08-03

Scanning the drive for archives:
1 file, 130085915 bytes (125 MiB)

Extracting archive: C:\spc2\downloads\icu-static-windows-x64.zip
--
Path = C:\spc2\downloads\icu-static-windows-x64.zip
Type = zip
Physical Size = 130085915

Everything is Ok

Folders: 5
Files: 227
Size:       454453649
Compressed: 130085915
[12:41:09] [D] scanning directory C:\Users\User\AppData\Local\Temp\spc_unzip_c0a0c760ee5e04729a8fd92684e222f6
[12:41:09] [D] Removing path recursively: "C:\spc2\source\icu-static-win"
[12:41:09] [D] scanning directory C:\spc2\source\icu-static-win
[12:41:09] [D] Removing path recursively: "C:\Users\User\AppData\Local\Temp\spc_unzip_c0a0c760ee5e04729a8fd92684e222f6"
[12:41:09] [D] scanning directory C:\Users\User\AppData\Local\Temp\spc_unzip_c0a0c760ee5e04729a8fd92684e222f6
[12:41:10] [W] PHP Warning: copy(C:\spc2\source\icu-static-win\x64-windows-static\lib\icudt.lib): Failed to open stream: No such file or directory in phar://C:/spc2/spc.exe/src/SPC/builder/windows/library/icu_static_win.php on 15
[12:41:10] [W] PHP Warning: copy(C:\spc2\source\icu-static-win\x64-windows-static\lib\icuin.lib): Failed to open stream: No such file or directory in phar://C:/spc2/spc.exe/src/SPC/builder/windows/library/icu_static_win.php on 16
[12:41:10] [W] PHP Warning: copy(C:\spc2\source\icu-static-win\x64-windows-static\lib\icuio.lib): Failed to open stream: No such file or directory in phar://C:/spc2/spc.exe/src/SPC/builder/windows/library/icu_static_win.php on 17
[12:41:10] [W] PHP Warning: copy(C:\spc2\source\icu-static-win\x64-windows-static\lib\icuuc.lib): Failed to open stream: No such file or directory in phar://C:/spc2/spc.exe/src/SPC/builder/windows/library/icu_static_win.php on 18
[12:41:10] [D] Copying directory from C:\spc2\source\icu-static-win\x64-windows-static\include\unicode to C:\spc2\buildroot\include\unicode
[12:41:10] [D] [PASSTHRU] xcopy "C:\spc2\source\icu-static-win\x64-windows-static\include\unicode" "C:\spc2\buildroot\include\unicode" /s/e/y/i
File not found - unicode
0 File(s) copied
✗ Command execution failed: Direct command run failed with code: 4
----------------------------------------

Failed module: library icu-static-win builder for Windows

Failed command: xcopy "C:\spc2\source\icu-static-win\x64-windows-static\include\unicode" "C:\spc2\buildroot\include\unicode" /s/e/y/i

Build PHP extra info:
    Build OS:               Windows (AMD64)
    Build Target:           native-windows
    Build Toolchain:        SPC\toolchain\MSVCToolchain
    Build SAPI:             cli
    Static Extensions (32): bcmath,brotli,bz2,ctype,zlib,openssl,curl,iconv,xml,dom,exif,fileinfo,filter,ftp,gd,intl,mbstring,mysqlnd,mysqli,pdo,pdo_mysql,pgsql,pdo_pgsql,sqlite3,pdo_sqlite,session,simdjson,simplexml,sodium,tokenizer,xmlwriter,zip
    Shared Extensions (0):  ""
    Libraries (22):         brotli,bzip2,zlib,openssl,libssh2,libiconv-win,libxml2,nghttp2,curl,libpng,libjpeg,freetype,icu-static-win,postgresql-win,sqlite,libsodium,xz,libzip
    Strip Binaries:         yes
    Enable ZTS:             no
    PHP Version:            8.3.30

Builder function: setupLibs

----------------------------------------

⚠ The console output log is saved in C:\spc2\log\spc.output.log
⚠ The shell output log is saved in C:\spc2\log\spc.shell.log

C:\spc2>                                                                                                                                                                        
```

Already Googled it and tried to solve it with AI but the errors just keep getting longer, and I don't know why. Maybe someone can help

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

- Closes #1084
- Closes #1060 
- Closes #1083 
- Fix https://github.com/static-php/static-php-cli-hosted/actions/runs/24224488409/job/70722738151#step:11:29067

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [x] `composer cs-fix`
  - [x] `composer analyse`
  - [x] `composer test`
  - [ ] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [x] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

**Review by henderkes — APPROVED** [review]

**Comment by henderkes** [comment]
run CI test please

**Comment by henderkes** [comment]
Just realized that macOS runners are still using Clang 17. Should really update to 19+ for vastly improved performance.

**Comment by crazywhalecc** [comment]
> Just realized that macOS runners are still using Clang 17. Should really update to 19+ for vastly improved performance.

I already introduced a env var to handle this on v3, it will automatically use homebrew version of llvm.

https://github.com/crazywhalecc/static-php-cli/blob/7e2cfe2950a85ffb9bb0208dba70cd63c310e518/config/env.ini#L137-L138

File: src/SPC/builder/unix/library/libjpeg.php [hunk 1]
```diff
@@ -14,7 +14,10 @@ protected function build(): void
             ->addConfigureArgs(
                 '-DENABLE_STATIC=ON',
                 '-DENABLE_SHARED=OFF',
-                '-DWITH_SYSTEM_ZLIB=ON'
+                '-DWITH_SYSTEM_ZLIB=ON',
+                '-DWITH_TOOLS=OFF',
+                '-DWITH_TESTS=OFF',
+                '-DWITH_SIMD=OFF',
```
Comment (henderkes) [inline src/SPC/builder/unix/library/libjpeg.php:20]: we have a variable for whether avx2/avx512 are enabled

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libjpeg.php:20]: Which one?

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libjpeg.php:20]: Found it: 
```
$code = '#include <immintrin.h>
int main() { return _mm256_cvtsi256_si32(_mm256_setzero_si256()); }';
        $cc = getenv('CC') ?: 'gcc';
        [$ret] = shell()->execWithResult("printf '%s' '{$code}' | {$cc} -x c -mavx2 -o /dev/null - 2>&1");
        $disableAvx2 = $ret !== 0 && GNU_ARCH === 'x86_64' && PHP_OS_FAMILY === 'Linux';
```

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libjpeg.php:20]: It seems better to abstract it into a separate method on v3 and pass it using environment variables.

Comment (henderkes) [reply src/SPC/builder/unix/library/libjpeg.php:20]: We should do it like php-src. There's a `--enable-native-intrinsics=level` switch that defines what level will be chosen.

Levels are SSE2 (default on x86), SSE3...4.2, AVX2, AVX512. On aarch64 I forgot the names something like neonv8.

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libjpeg.php:20]: We can create a separate issue tracking it though
