### PR TITLE
Fix CraftCommand ignoring build-options during build

### LINKED ISSUE #732: CraftCommand does not forward build-options to build command
Given the following `craft.yml`:
```yaml
php-version: 8.4
extensions: "curl"
sapi: cli
build-options:
  with-clean: false
  prefer-pre-built: true
  with-config-file-path: /custom/config/path
```

I'd expect the following build process to be executed:
```sh
'/usr/local/bin/php' 'bin/spc' 'build' '--no-motd' 'curl' '--with-libs=' '--build-cli' '--with-suggested-libs' '--with-config-file-path="/custom/config/path"'
```

But the actual process looks like this:
```sh
'/usr/local/bin/php' 'bin/spc' 'build' '--no-motd' 'curl' '--with-libs=' '--build-cli'
```

I'll shortly push a fix.

### PR DESCRIPTION
**Pull request by vworldat**
## What does this PR do?

At the moment, it's impossible to pass build-options when using `spc craft` (see #732). This PR fixes that, allowing the following use cases:

- boolean `true` values such as `--with-suggested-libs` are passed without parameters, assuming `InputOption::VALUE_NONE` behaviour.
- boolean `false` values (e.g. when setting `with-suggested-libs: false` in `yaml`) are omitted since Symfony console treats those values as opt-in only.
- array values are treated as "add this option multiple times". Tested with `with-hardcoded-ini`.
- everything else is passed as `--param=value`.

Works fine locally both with `spc` as well as `spc-alpine-docker`.

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- [x] If you modified `*.php`, run `composer cs-fix` at local machine.
- [ ] If it's an extension or dependency update, make sure adding related extensions in `src/global/test-extensions.php`.
- [ ] If you changed the behavior of static-php-cli, update docs in `./docs/`.
- [ ] If you updated `config/xxx.json` content, run `bin/spc dev:sort-config xxx`.

Closes #732

### CODE REVIEW

**Comment by henderkes** [comment]
looks good to me

File: src/SPC/command/CraftCommand.php [hunk 1]
```diff
@@ -104,6 +104,25 @@ public function handle(): int
...
+                if (is_array($value)) {
+                    foreach ($value as $subVal) {
+                        $args[] = "--{$option}={$subVal}";
+                    }
+
+                    continue;
+                }
+
+                $args[] = "--{$option}={$value}";
+            }
```
Comment (crazywhalecc) [inline src/SPC/command/CraftCommand.php:125]: https://github.com/crazywhalecc/static-php-cli/blob/ca3d6d14d0b8df5ad04b881fbdaa50f6ad661a3f/src/SPC/command/CraftCommand.php#L83-L95

Seems we could extract this option parsing in a separate function, just re-use this section.

**Review by crazywhalecc — CHANGES_REQUESTED** [review]
