### PR TITLE
Fix grpc build

### LINKED ISSUE #1054: ext-grpc build failed on macOS and Linux
```
bin/spc download --for-extensions=grpc
bin/spc build grpc --build-cli --debug
```

For Linux, using zig toolchain will get different error.

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Closes #1054

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [ ] `composer cs-fix`
  - [ ] `composer analyse`
  - [ ] `composer test`
  - [ ] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [X] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

**Comment by crazywhalecc** [comment]
Using ext-grpc to compile all grpc dependencies looks not good for our build procedure.

First of all, it's too slow for building static php binary every time. Building separately could reduce a lot of time when debugging and publishing. And another potential issue is building openssl, libcares and zlib twice. And also, although we can make a patch for boringssl and openssl built by grpc source to solve the CI error above, it often leads to misleading errors when building in-tree ext-grpc with all dependencies.

**Comment by henderkes** [comment]
I know, but the extension is just shit. There's nothing we can do about it, short of completely replacing the extension build logic. We built the library standalone before, but the extension build doesn't use prebuilt libraries, it builds every time no matter what.

File: src/SPC/builder/extension/grpc.php [hunk 1]
```diff
@@ -21,18 +20,50 @@ public function patchBeforeBuildconf(): bool
...
+      PHP_ADD_LIBRARY(rt,,GRPC_SHARED_LIBADD)
+      PHP_ADD_LIBRARY(rt)
+      ;;
+    esac
+
+  PHP_NEW_EXTENSION(grpc, @grpc_c_files@, $ext_shared, , -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1)
+  PHP_SUBST(GRPC_SHARED_LIBADD)
+  PHP_INSTALL_HEADERS([ext/grpc], [php_grpc.h])
+fi
+M4;
```
Comment (henderkes) [inline src/SPC/builder/extension/grpc.php:58]: Very ugly, but the best we can do at this point. We will need to keep it in sync with version changes, though.

File: src/globals/test-extensions.php [hunk 2]
```diff
@@ -16,15 +16,15 @@
     // '8.1',
     // '8.2',
     // '8.3',
```
Comment (henderkes) [inline src/globals/test-extensions.php:18]: did you test for 8.3 too? 8.2 can be ignored.

Comment (crazywhalecc) [reply src/globals/test-extensions.php:18]: I even tested it locally on version 8.0, and this m4 basically has maximum compatibility.

File: src/SPC/builder/extension/grpc.php (hunk 1 above)
Comment (crazywhalecc) [reply src/SPC/builder/extension/grpc.php:58]: Yes, and for now, unless it changes the interface, we can tolerate it adding new files. It's ugly, but much simpler than patching the original files.
