### PR TITLE
Fix gettext on locale bug

### LINKED ISSUE #631: gettext extension fails test
```console
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n -r "assert(function_exists('filter_var'));"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:191
[05:26:34] [I] testing ext: ftp
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n --ri "ftp"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:178
[05:26:34] [I] testing ext: gd
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n --ri "gd"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:178
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n -r "assert(function_exists('gd_info'));\$info = gd_info();assert(\$info['PNG Support'] ?? false);assert(\$info['GIF Create Support'] ?? false);assert(\$info['GIF Read Support'] ?? false);"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:191
[05:26:34] [I] testing ext: gettext
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n --ri "gettext"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:178
[05:26:34] [I] [EXEC] /app/buildroot/bin/php -n -r "assert(function_exists('gettext'));assert(function_exists('bindtextdomain'));assert(function_exists('textdomain'));if ("'!'"is_dir('locale/en_US/LC_MESSAGES/')) {    mkdir('locale/en_US/LC_MESSAGES/', 0755, true);}if ("'!'"file_exists('locale/en_US/LC_MESSAGES/test.mo')) {    \$mo = '3hIElQAAAAACAAAAHAAAACwAAAAFAAAAPAAAAAAAAABQAAAABgAAAFEAAAAXAQAAWAAAAAcAAABwAQAAAQAAAAAAAAAAAAAAAgAAAAAAAAAA56S65L6LAFByb2plY3QtSWQtVmVyc2lvbjogUEFDS0FHRSBWRVJTSU9OClJlcG9ydC1Nc2dpZC1CdWdzLVRvOiAKUE8tUmV2aXNpb24tRGF0ZTogWUVBUi1NTy1EQSBITzpNSStaT05FCkxhc3QtVHJhbnNsYXRvcjogRlVMTCBOQU1FIDxFTUFJTEBBRERSRVNTPgpMYW5ndWFnZS1UZWFtOiBMQU5HVUFHRSA8TExAbGkub3JnPgpMYW5ndWFnZTogCk1JTUUtVmVyc2lvbjogMS4wCkNvbnRlbnQtVHlwZTogdGV4dC9wbGFpbjsgY2hhcnNldD1VVEYtOApDb250ZW50LVRyYW5zZmVyLUVuY29kaW5nOiA4Yml0CgBFeGFtcGxlAA==';    file_put_contents('locale/en_US/LC_MESSAGES/test.mo', base64_decode(\$mo));}putenv('LANG=en_US');setlocale(LC_ALL, 'en_US');\$domain = 'test';bindtextdomain(\$domain, 'locale/');textdomain(\$domain);assert(gettext(json_decode('\"\u793a\u4f8b\"', true)) === 'Example');"
[05:26:34] [I] Executed at: /app/src/SPC/builder/Extension.php:191
array(6) {
  [0]=>
  string(0) ""
  [1]=>
  string(129) "Fatal error: Uncaught AssertionError: assert(gettext(json_decode('"\\u793a\\u4f8b"', true)) === 'Example') in Command line code:1"
  [2]=>
  string(12) "Stack trace:"
  [3]=>
  string(60) "#0 Command line code(1): assert(false, 'assert(gettext(...')"
  [4]=>
  string(9) "#1 {main}"
  [5]=>
  string(39) "  thrown in Command line code on line 1"
}
[05:26:34] [I] Uncaught SPC\exception\RuntimeException: extension gettext failed sanity check at /app/src/SPC/builder/Extension.php(196)
[05:26:34] [I] #0 /app/src/SPC/builder/unix/UnixBuilderBase.php(151): SPC\builder\Extension->runCliCheckUnix()
#1 /app/src/SPC/builder/linux/LinuxBuilder.php(221): SPC\builder\unix\UnixBuilderBase->sanityCheck(9)
#2 /app/src/SPC/command/BuildCliCommand.php(184): SPC\builder\linux\LinuxBuilder->buildPHP(9)
#3 /app/src/SPC/command/BaseCommand.php(106): SPC\command\BuildCliCommand->handle()
#4 /app/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildCliCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/bin/spc(31): Symfony\Component\Console\Application->run()
#9 {main}
```

When run in spc-gnu-docker

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Fix #631 .

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- [X] If you modified `*.php`, run `composer cs-fix` at local machine.
- [X] If it's an extension or dependency update, make sure adding related extensions in `src/global/test-extensions.php`.
- [ ] If you changed the behavior of static-php-cli, update docs in `./docs/`.
- [ ] If you updated `config/xxx.json` content, run `bin/spc dev:sort-config xxx`.

### CODE REVIEW

File: src/SPC/builder/unix/library/attr.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ protected function build(): void
                 'LDFLAGS' => trim('-L' . BUILD_LIB_PATH . ' ' . $this->getLibExtraLdFlags()),
                 'LIBS' => $this->getLibExtraLibs(),
             ])->execWithEnv('./autogen.sh')
-            ->execWithEnv('./configure --prefix= --enable-static --disable-shared')
+            ->execWithEnv('./configure --prefix= --enable-static --disable-shared --with-pic --without-libintl-prefix --without-libiconv-prefix')
```
Comment (DubbleClick) [inline src/SPC/builder/unix/library/attr.php:22]: see my other PR, I think that's the besser solution. disabling nls should prevent it from looking for intl or iconv.

**Comment by crazywhalecc** [comment]
That's another build failure, in gnu docker....

```
[10:28:46] [I] [EXEC] CFLAGS="-I/app/buildroot/include -fPIE -fPIC" LDFLAGS="-L/app/buildroot/lib" ./autogen.sh
[10:28:46] [I] Executed at: /app/src/SPC/util/UnixShell.php:88
[10:28:46] [I] [PASSTHRU] cd '/app/source/attr' && CFLAGS="-I/app/buildroot/include -fPIE -fPIC" LDFLAGS="-L/app/buildroot/lib" ./autogen.sh
+ po/update-potfiles
+ autopoint --force
Copying file ABOUT-NLS
Creating directory build-aux
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
++ automake --print-libdir
+ am_libdir=/usr/local/share/automake-1.17
+ cp /usr/local/share/automake-1.17/INSTALL doc/
+ exec autoreconf -f -i
configure.ac:37: installing 'build-aux/ar-lib'
configure.ac:28: installing 'build-aux/compile'
configure.ac:27: installing 'build-aux/config.guess'
configure.ac:27: installing 'build-aux/config.sub'
configure.ac:24: installing 'build-aux/install-sh'
configure.ac:24: installing 'build-aux/missing'
Makefile.am:19: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:19:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:19:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:19: 
Makefile.am:19:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:19:   its definition is in aclocal's search path.
Makefile.am:19: 
Makefile.am:19:   If you install Automake in its own prefix,
Makefile.am:19:   you'll need to arrange for the Libtool m4 files
Makefile.am:19:   to be found by aclocal.  For info on this, see:
Makefile.am:19:     https://gnu.org/s/automake/manual/automake.html#Libtool-library-used-but-LIBTOOL-is-undefined
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
[10:28:49] [I] Uncaught SPC\exception\RuntimeException: Command run failed with code[1]: cd '/app/source/attr' && CFLAGS="-I/app/buildroot/include -fPIE -fPIC" LDFLAGS="-L/app/buildroot/lib" ./autogen.sh at /app/src/globals/functions.php(166)
```

**Comment by DubbleClick** [comment]
I don't think the last commit is the right approach. Let the system tools handle that.

Install gettext-devel and libtool

**Comment by crazywhalecc** [comment]
> Install gettext-devel and libtool

I tried, but it got an error `Makefile.am:19: error: Libtool library used but 'LIBTOOL' is undefined` like this when I use `./autogen.sh`.

**Comment by DubbleClick** [comment]
I think if you revert

```php
            ->execWithEnv('po/update-potfiles')
            ->execWithEnv('aclocal')
            ->execWithEnv('libtoolize --force --copy')
            ->execWithEnv('autoreconf --force --install')
 ```
 
 it should work now.

**Comment by DubbleClick** [comment]
Okay, I'll take it over tomorrow
