### PR TITLE
Fix libde265 on arm64 macOS asm build bug

### LINKED ISSUE #1116: Unable to build libde265 on ARM64 macOS
Hey!

I am trying to build PHP 8.5 (also fails on 8.4) but get an error with libde265 in my GitHub action workflow.

**Operating System:** macOS 14.8.5 (also fails on 15.x)
**GitHub Image:** `macos-14-arm64`
**GitHub Image Version:** `20260413.0223.1`
**Extension list:**
```
intl,pdo_sqlite,sqlite3,curl,openssl,tokenizer,bcmath,bz2,calendar,dba,ftp,iconv,mysqli,mbstring,mbregex,xml,simplexml,ctype,dom,pdo,filter,session,zlib,fileinfo,pdo_mysql,posix,sockets,shmop,sodium,sysvmsg,sysvsem,sysvshm,gd,zip,gmp,redis,xmlwriter,phar,exif,xmlreader,readline,pcntl,soap,imagick,ffi,password-argon2,pgsql,pdo_pgsql,imap,ldap,xsl,igbinary,zstd,gettext,mongodb,sqlsrv,pdo_sqlsrv,opcache
```

Error from log: https://gist.github.com/mpociot/aacdaaa81cd6e73760007527a09aafff

Reproduced with the latest nightly and stable build of static-php-cli.

I was able to fix this (with the help of AI) by modifying `macos/library/libde265.php` and add:

```
'-DHAVE_ARM=OFF'
```

But I'm not sure if this is really the right way to prevent this from happening.

### PR DESCRIPTION
**Pull request by crazywhalecc**
## What does this PR do?

Closes #1116 

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- If you modified `*.php` or `*.json`, run them locally to ensure your changes are valid:
  - [ ] `composer cs-fix`
  - [ ] `composer analyse`
  - [ ] `composer test`
  - [ ] `bin/spc dev:sort-config`
- If it's an extension or dependency update, please ensure the following:
  - [X] Add your test combination to `src/globals/test-extensions.php`.
  - [ ] If adding new or fixing bugs, add commit message containing `extension test` or `test extensions` to trigger full test suite.

### CODE REVIEW

File: src/SPC/builder/unix/library/libde265.php [hunk 1]
```diff
@@ -13,7 +13,8 @@ protected function build(): void
         UnixCMakeExecutor::create($this)
             ->addConfigureArgs(
                 '-DENABLE_SDL=OFF',
-                '-DENABLE_DECODER=OFF'
+                '-DENABLE_DECODER=OFF',
+                '-DHAVE_ARM=OFF',
```
Comment (henderkes) [inline src/SPC/builder/unix/library/libde265.php]: perhaps do this on mac only? neon are generally helpful in my builds on rhel 9 & 10

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libde265.php]: Linux aarch64 may also have this bug though.

However, considering this chain: libde265-libheif-imagemagick-imagick, the only function of libde265 assembly should be HEVC/HEIF things. I'm not sure if adding this assembly is worthwhile for the benefit of this extension. In any case, arm64 assembly is likely missing, it only has armv7 assembly. x86 assembly is compatible with x64, which may explain why it has consistently compiled successfully.

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libde265.php]: Oh wait, libde265 have `HAVE_NEON` option, this looks more accurate, and we don't worry about x86, it just because it depends on `HAVE_ARM` which is negative on x86. Let me change to `HAVE_NEON=OFF`.

```suggestion
                '-DHAVE_NEON=OFF',
```

Comment (henderkes) [reply src/SPC/builder/unix/library/libde265.php]: @mpociot does this still fix your issue?

Comment (mpociot) [reply src/SPC/builder/unix/library/libde265.php]: No, still fails for me with `HAVE_NEON=OFF`

Comment (crazywhalecc) [reply src/SPC/builder/unix/library/libde265.php]: > No, still fails for me with HAVE_NEON=OFF

With clean downloads and without pre-built content? (cannot contain `--prefer-pre-built` option)

Comment (mpociot) [reply src/SPC/builder/unix/library/libde265.php]: Sorry, looks like it wasn't the proper build 🤦 
Yes, I can confirm - this fix works too 👍

**Review by henderkes — APPROVED** [review]
I'd still prefer to make this macOS only for now.
